#!/usr/bin/env ruby

require 'netrc'
require 'nokogiri'
require 'open-uri'
require 'uri'

URL = 'http://omegachess.ru/omega/games.php'
HOST = URI.parse(URL).host

n = Netrc.read[HOST]
unless n and n.login
  abort "~/.netrc should include: machine #{HOST} login [...]"
end
user = n.login

nb_pending_games = 0

doc = Nokogiri::HTML(open(URL))
doc.xpath('//table/tr').drop(1).each do |row|
  players = {
    'white' => row.at_xpath('td[3]/text()').to_s,
    'black' => row.at_xpath('td[4]/text()').to_s
  }

  if players.values.include? user
    current_move = row.at_xpath('td[6]/text()').to_s
    if players[current_move] == user
      nb_pending_games += 1
    end
  end
end

puts nb_pending_games
