#!/usr/bin/env ruby

require 'getoptlong'
require 'netrc'
require 'nokogiri'
require 'open-uri'
require 'uri'

URL = 'http://omegachess.ru/omega/games.php'
HOST = URI.parse(URL).host

##### Argument parsing

def usage()
  abort "Usage: #$0 [--genmon]"
end

options = {}
GetoptLong.new(
  ['--help', '-h', GetoptLong::NO_ARGUMENT],
  ['--genmon', GetoptLong::NO_ARGUMENT]
).each do |name, value|
  options[name.sub(/^--/, '').to_sym] = value
end

if options[:help] or not ARGV.empty?
  usage
end

##### Main program

n = Netrc.read[HOST]
unless n and n.login
  abort "~/.netrc should include: machine #{HOST} login [...]"
end
user = n.login

nb_pending_games = 0

begin
  doc = Nokogiri::HTML(URI.open(URL))
rescue Exception => e
  if options[:genmon]
    puts '?'
    exit 1
  else
    raise e
  end
end

doc.xpath('//table/tr').drop(1).each do |row|
  players = {
    'white' => row.at_xpath('td[3]/text()').to_s,
    'black' => row.at_xpath('td[4]/text()').to_s
  }

  if players.values.include? user
    current_move = row.at_xpath('td[6]/text()').to_s
    if players[current_move] == user
      nb_pending_games += 1
    end
  end
end

if options[:genmon] and nb_pending_games > 0
  # thanks https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674727
  puts %Q{<txt><span color="red">#{nb_pending_games}</span></txt>}
else
  puts nb_pending_games
end
